version: 0.2
  
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build Docker Image alpha-bdx-import Started
      - docker build -t $AWS_DOCKER_NAME:$AWS_DOCKER_TAG .
  post_build:
    commands:
      - echo Start pushing to repository
      - docker tag $AWS_DOCKER_NAME:$AWS_DOCKER_TAG $AWS_REPOSITORY_NAME:$AWS_REPOSITORY_TAG
      - docker push $AWS_REPOSITORY_NAME:$AWS_REPOSITORY_TAG