version: 0.2

phases:
  versioning:
    commands:
      - $PROJECT_VERSION= (./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
  build:
    commands:
      - echo Build Docker Image alpha-bdx-import:`$PROJECT_VERSION` Started at `date`