version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build Docker Image $ALPHA_IMAGE_NAME Started at `date`
      - docker build --build-arg jar_name=$ALPHA_IMAGE_NAME -t $ALPHA_IMAGE_NAME:$ALPHA_IMAGE_TAG .
  post_build:
    commands:
      - docker tag $ALPHA_IMAGE_NAME:latest $ALPHA_REPOSITORY
      - docker push $ALPHA_REPOSITORY