version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build Docker Image alpha-bdx-import Started at `date`
      - docker build -t alpha-bdx-import:latest .
  post_build:
    commands:
      - docker tag alpha-bdx-import:latest 925851410669.dkr.ecr.eu-west-3.amazonaws.com/backend/alpha-bdx-import:latest
      - docker push 925851410669.dkr.ecr.eu-west-3.amazonaws.com/backend/alpha-bdx-import:latest