version: 0.2

phases:
  pre_build:
    commands:
      - PROJECT_VERSION= ./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec
      - echo Project is on this version $PROJECT_VERSION
  build:
    commands:
      - echo Build Docker Image alpha-bdx-import:$PROJECT_VERSION Started at `date`